sudo: required
language: node_js

services:
  - docker
env:
  - CI:true

before_install:
  - docker build -t corourke/docker-services-test -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run corourke/docker-services-test npm test -- --coverage

after_success:
  - docker build -t corourke/dst-frontend ./frontend
  - docker build -t corourke/dst-api ./api-server
  - docker build -t corourke/dst-nginx ./nginx
  - docker build -t corourke/dst-worker ./worker
  # Log in to docker cli
  - docker login -u "$USERNAME" -p "$PASSWORD"
  # Push images to docker hub
  - docker push corourke/dst-frontend
  - docker push corourke/dst-api
  - docker push corourke/dst-nginx
  - docker push corourke/dst-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: docker-services-test
  env: DockerServicesTest-env
  bucket-name: elasticbeanstalk-us-east-2-045586879042
  bucket-path: docker-services-test
  on:
      branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
